### ISSUE TITLE
undefined method model exists on rails g devise_two_factor  <model name>

### ISSUE THREAD

**Issue by aki1221** [williamatodd/devise-2fa#16]
/devise_two_factor_generator.rb:19:in `inject_field_types': undefined method `model_exists?' for #<ActiveRecord::Generators::DeviseTwoFactorGenerator:0x00007fd2c317e6c8> (NoMethodError)

**Comment by williamatodd** [comment]
@aki1221 can you provide a little more background for this issue?  eg. steps to reproduce, full backtrace, etc?

**Comment by aki1221** [comment]
@williamatodd  sure, 
steps to reproduce
1.create a project with rails 6 and ruby 2.6 and setup devise
2.install devise -2fa gem 
3. on running rails g devise_two_factor:install (will give adepriciation warning)
4.running rails g devise_two_factor User will raise the above error

**Comment by williamatodd** [comment]
@aki1221 I'm seeing the same exception.  When you encountered this problem, did the generator produce a migration file and insert :two_factorable into the User's Devise configuration?

**Comment by williamatodd** [comment]
@aki1221 nevermind.  I'm just going to fix the issue and release a new version.  Thank you for the report.
